### ISSUE TITLE
Not huge issues, but 3 little things that maybe could be polished!

### ISSUE THREAD

**Issue by samcaron55** [Comfy-Themes/Discord#120]
1. The "User Settings" label that appears when you hover goes off-screen. Insert a line break, or maybe simply rename it "Settings"?
2. The user avatar next to the message bar is blurry, but all the other avatars on the chat are not. Would be great if there was a fix!
3. When you click on an image and the window is darker. The "minimize, restore and close" buttons are in front of the dark effect and don't get darker.

Overall, love the theme and I will keep using it regardless! These are just little nitpicks. Thank you for making such cool themes <3

**Comment by NYRI4** [comment]
1. The issue with themes is that we can only deal with what is already in the DOM and nothing else, that's how it is when CSS only is authorized, since there's no classes to target this specific element and do whatever you said above, I can't do anything particular , otherwise it would those changes would be on all the smalls hints called tooltips. 

Example : 
| First tooltip | Second tooltip |
| ------------- | ------------- |
| ![image](https://github.com/Comfy-Themes/Discord/assets/65369563/379ca2f9-bcd1-4e6f-ad86-7324608b956a) | ![image](https://github.com/Comfy-Themes/Discord/assets/65369563/cdc00df6-5a53-4867-ab2c-4eafdece05de) |

2. Sadly, some years ago Discord added a size argument when fetching their images for performances concerns (Example : https://cdn.discordapp.com/avatars/265924886461939712/3a5a7e7498d256fe883629b6b18f9643.webp?size=40 with the `size=40`) at the end, if you open this image you'll see what is supposed to be next to messages. (Of course CSS can't modify links since it would be a huge security issue).

3. Actually it's the same with basic Discord, it's just less obvious, will be fixed in the next push.

Thanks for the support and feedback about the theme <3

**Comment by ohitstom** [comment]
not a discord modder here but if tippy is exposed in js you can easily remove them, or using the :has selector.

**Comment by Metro420yt** [comment]
For 1, I noticed it and made a quick fix #126
